version: 0.2
phases:
  install:
    commands:
      - echo "Iniciando Deploy"
  build:
    commands:
      - echo "Desplegando app a EC2"
      - mkdir -p /tmp/app
      - aws s3 cp s3://$S3_BUCKET/app.zip /tmp/app/app.zip
      - unzip -o /tmp/app/app.zip -d /tmp/app/
      - echo "verificando descomprension exitosa"
      - test -f /tmp/app/index.html || exit 1

post_build:
  commands: 
    - echo "aplicando deploy a ec2 via SSM"
    - |
      aws ssm send-command \
        --instance-ids $INSTANCE_ID \
        --document-name "AWS-RunShellScript" \
        --comment "desplegando web" \
        --parameters 'commands=[
          "sudo cp -r /tmp/app/* /var/www/html/",
          "sudo chown -R www-data:www-data /var/www/html/ || true",
          "if sudo systemctl is-active apache2 >/dev/null 2>&1; then sudo systemctl restart apache2; elif sudo systemctl is-active httpd >/dev/null 2>&1; then sudo systemctl restart httpd; fi"
          ]'  \

          --timeout-seconds 600

artifacts:
  files:
    - '**/*'

