version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependencias (si las hubiera)"
  build:
    commands:
      - echo "Contenido del directorio antes de zip"
      - ls -la
      - echo "Empaquetando aplicación"
      - zip -r app.zip *
      - echo "Contenido del zip para debug"
      - unzip -l app.zip
  post_build:
    commands:
      - echo "Verificando que app.zip fue generado"
      - test -f app.zip || exit 1
artifacts:
  files:
    - app.zip
