version: 0.2

phases:
  install:
    commands:
      - echo "Iniciando build"
  build:
    commands:
      - echo "Contenido del directorio antes de zip:"
      - ls -l
      - echo "Empaquetando aplicación"
      - zip -r app.zip *
      - echo "Contenido del zip para debug"
      - unzip -l app.zip
  post_build:
    commands:
      - echo "Verificando que app.zip fue generado"
      - test -f app.zip || exit 1
      - echo "Subiendo app.zip a S3 solo si todo está correcto"
      - aws s3 cp app.zip s3://$S3_BUCKET/app.zip
artifacts:
  files:
    - '**/*'
