version: 0.2

phases:
  install:
    commands:
      - echo "Iniciando build"
  build:
    commands:
      - echo "Empaquetando aplicación"
      - zip -r app.zip *
  post_build:
    commands:
      - echo "Subiendo app.zip a S3"
      - aws s3 cp app.zip s3://$S3_BUCKET/app.zip
artifacts:
  files:
    - app.zip
